services:
  mysql:
    image: mysql
    container_name: bendy_db
    restart: always
    environment:
      MYSQL_DATABASE: bendy_db
      MYSQL_USER: gusalmonacid
      MYSQL_PASSWORD: Cala_Underplayer2004
      MYSQL_ROOT_PASSWORD: Cala_Underplayer2004
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: