version: '3.8'

services:
  postgres:
    image: postgres
    container_name: bendy_db
    restart: always
    environment:
      POSTGRES_DB: bendy_db
      POSTGRES_USER: gusalmonacid
      POSTGRES_PASSWORD: Cala_Underplayer2004
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: