# Generated by Django 6.0.5 on 2026-05-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bendy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='Identificador único para URLs (ej: bendy-the-dancing-demon)', unique=True, verbose_name='Slug')),
                ('alias', models.CharField(blank=True, help_text='Otros nombre por los que se conoce al personaje', max_length=200, verbose_name='Alias')),
                ('game', models.CharField(choices=[('batim', 'Bendy and the Ink Machine'), ('batdr', 'Bendy and the Dark Revival'), ('both', 'Ambos')], default='batim', help_text='En qué juego(s) aparece este personaje', max_length=10, verbose_name='Juego')),
                ('role', models.CharField(choices=[('protagonist', 'Protagonista'), ('antagonist', 'Antagonista'), ('secondary_antagonist', 'Antagonista secundario'), ('ally', 'Aliado'), ('neutral', 'Neutral'), ('mentioned', 'Solo mencionado')], default='secondary_antagonist', max_length=30, verbose_name='Rol')),
                ('character_type', models.CharField(choices=[('human', 'Humano'), ('toon', 'Personaje de dibujos animados'), ('ink_monster', 'Monstruo de tinta'), ('hybrid', 'Híbrido'), ('spirit', 'Espíritu/Alma')], default='toon', max_length=20, verbose_name='Tipo de personaje')),
                ('description', models.TextField(help_text='Historia y contexto del personaje', verbose_name='Descripción general')),
                ('appearance', models.TextField(blank=True, help_text='Descripción física del personaje', verbose_name='Apariencia')),
                ('personality', models.TextField(blank=True, verbose_name='Personalidad')),
                ('background', models.TextField(blank=True, help_text='Historia previa del personaje antes de los eventos del juego', verbose_name='Trasfondo')),
                ('human_counterpart', models.CharField(blank=True, help_text='Nombre del humano en el que está basado (ej: Susie Campbell → Twisted Alice)', max_length=100, verbose_name='Contraparte humana')),
                ('voice_actor_batim', models.CharField(blank=True, max_length=100, verbose_name='Actor de voz (BATIM)')),
                ('voice_actor_batdr', models.CharField(blank=True, max_length=100, verbose_name='Actor de voz (BATDR)')),
                ('real_world_inspiration', models.CharField(blank=True, help_text='En que personaje real o histórico está basado (ej: Betty Boop → Alice Angel', max_length=200, verbose_name='Inspiración del mundo real')),
                ('appears_in_chapters', models.CharField(blank=True, help_text="EJ:'1, 2, 3' o 'Todos'", max_length=100, verbose_name='Aparece en capítulos')),
                ('iconic_quote', models.TextField(blank=True, verbose_name='Cita icónica')),
                ('quote_source', models.CharField(blank=True, help_text='De que parte del juego proviene la cita', max_length=100, verbose_name='Fuente de la cita')),
                ('is_alive_end', models.BooleanField(blank=True, default=True, null=True, verbose_name='¿Sobrevive al final?')),
                ('is_playable', models.BooleanField(default=False, verbose_name='¿Es jugable?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Personaje',
                'verbose_name_plural': 'Personajes',
                'ordering': ['game', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('batim', 'Bendy and the Ink Machine'), ('batdr', 'Bendy and the Dark Revival')], default='batim', max_length=10, verbose_name='Juego')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Número de capítulo')),
                ('title', models.CharField(help_text='Ej: Moving Pictures', max_length=150, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('art_theme', models.CharField(choices=[('animation', 'Animación / Dibujo'), ('music', 'Música'), ('literature', 'Literatura / Voz y diálogos'), ('scenography', 'Escenografía / Diseño de producción'), ('film', 'Séptimo arte / Cine'), ('none', 'Sin tema artístico explícito')], default='none', help_text='Cada capítulo de BATIM hace referencia a una forma de arte', max_length=20, verbose_name='Tema artístico')),
                ('art_theme_explanation', models.TextField(blank=True, verbose_name='Explicación del tema artístico')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Fecha de lanzamiento')),
                ('last_update_date', models.DateField(blank=True, help_text='Si el capítulo fue remasterizado o actualizado', null=True, verbose_name='Fecha de última actualización')),
                ('synopsis', models.TextField(verbose_name='Sinopsis')),
                ('aesthetic', models.TextField(blank=True, verbose_name='Estética y análisis visual')),
                ('setting_description', models.TextField(blank=True, help_text='Descripción del entorno físico donde transcurre el capítulo', verbose_name='Descripción del escenario')),
                ('difficulty', models.CharField(choices=[('introductory', 'Introductorio'), ('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil'), ('boss_heavy', 'Con múltiples jefes')], default='medium', max_length=20, verbose_name='Dificultad')),
                ('has_boss_fight', models.BooleanField(default=False, verbose_name='¿Tiene combate contra jefe?')),
                ('boss_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del jefe')),
                ('has_stealth_sections', models.BooleanField(default=False, verbose_name='¿Tiene secciones de sigilo?')),
                ('has_puzzle_sections', models.BooleanField(default=False, verbose_name='¿Tiene secciones de puzles?')),
                ('approximate_duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duración aproximada (minutos)')),
                ('protagonist', models.CharField(default='Henry Stein', max_length=100, verbose_name='Protagonista')),
                ('main_villain', models.CharField(blank=True, max_length=100, verbose_name='Villano principal')),
                ('new_characters_introduced', models.TextField(blank=True, help_text='Lista de personajes que aparecen por primera vez en este capítulo', verbose_name='Nuevos personajes introducidos')),
                ('key_events', models.TextField(blank=True, help_text='Los momentos más importantes del capítulo', verbose_name='Eventos clave')),
                ('lore_revelations', models.TextField(blank=True, help_text='Información nueva sobre la historia del mundo que se descubre en este capítulo', verbose_name='Revelaciones de trasfondo')),
                ('soundtrac_notes', models.CharField(blank=True, verbose_name='Notas sobre la banda sonora')),
                ('composer', models.CharField(blank=True, default='theMealty', max_length=100, verbose_name='Compositor')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='chapters/', verbose_name='Imagen de portada')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='chapters/backgrounds/', verbose_name='Imagen de fondo')),
                ('trivia', models.TextField(blank=True, verbose_name='Curiosidades / Trivia')),
                ('reception_notes', models.TextField(blank=True, help_text='Cómo reaccionó la comunidad al capítulo', verbose_name='Recepción / Polémica')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'ordering': ['game', 'number'],
                'unique_together': {('game', 'number')},
            },
        ),
    ]
