# Generated by Django 6.0.5 on 2026-05-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bendy_app', '0002_character_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='aesthetic',
            new_name='aesthetics',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='soundtrac_notes',
        ),
        migrations.AddField(
            model_name='chapter',
            name='soundtrack_notes',
            field=models.TextField(blank=True, verbose_name='Notas sobre la banda sonora'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='composer',
            field=models.CharField(blank=True, default='theMeatly', max_length=100, verbose_name='Compositor'),
        ),
        migrations.AlterField(
            model_name='character',
            name='alias',
            field=models.CharField(blank=True, help_text='Otros nombres por los que se conoce al personaje', max_length=200, verbose_name='Alias / Apodo'),
        ),
        migrations.AlterField(
            model_name='character',
            name='appears_in_chapters',
            field=models.CharField(blank=True, help_text="Ej: '1, 2, 3' o 'Todos'", max_length=100, verbose_name='Aparece en capítulos'),
        ),
        migrations.AlterField(
            model_name='character',
            name='is_alive_end',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Sobrevive al final?'),
        ),
        migrations.AlterField(
            model_name='character',
            name='quote_source',
            field=models.CharField(blank=True, help_text='De qué parte del juego proviene la cita', max_length=100, verbose_name='Fuente de la cita'),
        ),
        migrations.AlterField(
            model_name='character',
            name='real_world_inspiration',
            field=models.CharField(blank=True, help_text='En qué personaje real o histórico está basado (ej: Betty Boop → Alice Angel)', max_length=200, verbose_name='Inspiración del mundo real'),
        ),
    ]
