# Generated by Django 6.0.5 on 2026-05-25 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bendy_app", "0003_rename_aesthetic_chapter_aesthetics_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("batim", "Bendy and the Ink Machine"),
                            ("batdr", "Bendy and the Dark Revival"),
                        ],
                        help_text="Identificador corto del juego (batim / batdr)",
                        max_length=10,
                        unique=True,
                        verbose_name="Clave",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                (
                    "release_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Año de lanzamiento"
                    ),
                ),
                (
                    "short_description",
                    models.TextField(blank=True, verbose_name="Descripción corta"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, upload_to="games/", verbose_name="Imagen de Portada"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "Juego",
                "verbose_name_plural": "Juegos",
                "ordering": ["release_year"],
            },
        ),
        migrations.AlterModelOptions(
            name="character",
            options={
                "ordering": ["primary_game", "name"],
                "verbose_name": "Personaje",
                "verbose_name_plural": "Personajes",
            },
        ),
        migrations.RemoveField(
            model_name="character",
            name="game",
        ),
        migrations.AlterField(
            model_name="chapter",
            name="aesthetics",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="approximate_duration_minutes",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="art_theme",
            field=models.CharField(
                choices=[
                    ("animation", "Animación / Dibujo"),
                    ("music", "Música"),
                    ("literature", "Literatura / Voz y diálogos"),
                    ("scenography", "Escenografía / Diseño de producción"),
                    ("film", "Séptimo arte / Cine"),
                    ("none", "Sin tema artístico explícito"),
                ],
                default="none",
                max_length=20,
                verbose_name="Tema artístico",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="background_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="chapters/backgrounds/"
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="boss_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="composer",
            field=models.CharField(blank=True, default="theMeatly", max_length=100),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="chapters/"),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("introductory", "Introductorio"),
                    ("easy", "Fácil"),
                    ("medium", "Medio"),
                    ("hard", "Difícil"),
                    ("boss_heavy", "Con múltiples jefes"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="has_boss_fight",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="has_puzzle_sections",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="has_stealth_sections",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="key_events",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="last_update_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="lore_revelations",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="main_villain",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="new_characters_introduced",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="protagonist",
            field=models.CharField(default="Henry Stein", max_length=100),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="reception_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="setting_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="soundtrack_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="trivia",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="alias",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Alias / Apodo"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="appearance",
            field=models.TextField(blank=True, verbose_name="Apariencia"),
        ),
        migrations.AlterField(
            model_name="character",
            name="background",
            field=models.TextField(blank=True, verbose_name="Trasfondo"),
        ),
        migrations.AlterField(
            model_name="character",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="description",
            field=models.TextField(verbose_name="Descripción general"),
        ),
        migrations.AlterField(
            model_name="character",
            name="human_counterpart",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Contraparte humana"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="quote_source",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Fuente de la cita"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="real_world_inspiration",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Inspiración del mundo real"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="character",
            name="extra_games",
            field=models.ManyToManyField(
                blank=True,
                related_name="secondary_characters",
                to="bendy_app.game",
                verbose_name="También aparece en",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="primary_game",
            field=models.ForeignKey(
                default=str,
                help_text="Juego en el que el personaje tiene mayor protagonismo",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="characters",
                to="bendy_app.game",
                verbose_name="Juego principal",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chapter",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chapters",
                to="bendy_app.game",
                verbose_name="Juego",
            ),
        ),
        migrations.DeleteModel(
            name="BendyUser",
        ),
    ]
